name: Release docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:

  setup:
    uses: ./.github/workflows/shared.setup-env.yml

  docs:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-step
        with:
          set_shas: false

      - name: Build docs
        run: npx nx build documentation

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./dist/documentation # The folder the action should deploy.